// flow-typed signature: df165f1c4b64b2d8a24b2fb4671fff00
// flow-typed version: <<STUB>>/babel-plugin-dynamic-import-webpack_v^1.0.2/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-dynamic-import-webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-dynamic-import-webpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-dynamic-import-webpack/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-dynamic-import-webpack/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-dynamic-import-webpack/lib/index'>;
}
